package com.example.wearzone.domain.product.model

data class Product(
    val id: String,
    val variantId: String,
    val title: String,
    val vendor: String,
    val price: Double,
    val currencyCode: String,
    val imageUrl: String?,
    val isFavorite: Boolean = false,
    val productType: String = "",
    val tags: List<String> = emptyList(),
    val maxQuantity: Int = 0,
    val isOutOfStock: Boolean = false,
    val size: String? = null,
    val color: String? = null,
    val titleEn: String = title,
    val titleAr: String = "",
    val descriptionEn: String = "",
    val descriptionAr: String = "",
    val categoryEn: String = "",
    val categoryAr: String = "",
    val productTypeEn: String = productType,
    val productTypeAr: String = "",
)
